// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using control.Data;

#nullable disable

namespace control.Migrations
{
    [DbContext(typeof(controlContext))]
    [Migration("20231005154349_AddedFieldForUserCardId")]
    partial class AddedFieldForUserCardId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("DoorUser", b =>
                {
                    b.Property<string>("AccessDoorsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessUsers")
                        .HasColumnType("TEXT");

                    b.HasKey("AccessDoorsId", "AccessUsers");

                    b.HasIndex("AccessUsers");

                    b.ToTable("DoorUser");
                });

            modelBuilder.Entity("DoorUser1", b =>
                {
                    b.Property<string>("AdminDoorsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminUsers")
                        .HasColumnType("TEXT");

                    b.HasKey("AdminDoorsId", "AdminUsers");

                    b.HasIndex("AdminUsers");

                    b.ToTable("DoorUser1");
                });

            modelBuilder.Entity("control.Models.Door", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EntryStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastCheckInTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Registered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SelfRegisterAllowed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Door");
                });

            modelBuilder.Entity("control.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DoorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EntryResult")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DoorId");

                    b.HasIndex("UserName");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("control.Models.LoginLink", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GenerationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("LoginLink");
                });

            modelBuilder.Entity("control.Models.User", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AcceptedEula")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AccessCodeGenerationTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessCodeRetries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CompletedRegistration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserName");

                    b.ToTable("User");
                });

            modelBuilder.Entity("DoorUser", b =>
                {
                    b.HasOne("control.Models.Door", null)
                        .WithMany()
                        .HasForeignKey("AccessDoorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("control.Models.User", null)
                        .WithMany()
                        .HasForeignKey("AccessUsers")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoorUser1", b =>
                {
                    b.HasOne("control.Models.Door", null)
                        .WithMany()
                        .HasForeignKey("AdminDoorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("control.Models.User", null)
                        .WithMany()
                        .HasForeignKey("AdminUsers")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("control.Models.Log", b =>
                {
                    b.HasOne("control.Models.Door", "Door")
                        .WithMany()
                        .HasForeignKey("DoorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("control.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserName");

                    b.Navigation("Door");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
